<a href="https://colab.research.google.com/github/WYSTANich/PDA_sol-/blob/main/scipy_page_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Решение задач линейной алгебры в библиотеке SCIPY, 12 номер по списку

In [ ]:
#Задание1
import numpy as np
A = np.array([[2, 3 + 28, 4 - 1],
              [7, 3, 2],
              [5, 10 * 1, -2]])

B = np.array([[7, -3, 4 + 1],
              [28, 4, 2],
              [5 * 1, 10, -2]])

C = np.array([[-1, 3 + 1, 4 - 2],
              [2, 1, 2],
              [5, 5 - 1, -2]])
result_ABC = A @ B @ C

print("A * B * C =")
print(result_ABC)

A * B * C =
[[-271 4000 1958]
 [  64  731  234]
 [ -50 1421  522]]


In [ ]:
#Задание 2
from scipy.linalg import det, eig, inv
G = np.array([[2, 3 + 28, 4 + 1, 6],
              [7 + 1, 3, 2, 12],
              [5, -2, 16, 1 + 1],
              [2, 7, 11, -6]])
det_G = det(G)
eigenvalues_G, _ = eig(G)
inverse_G = inv(G)
print("\nОпределитель G:", det_G)
print("\nВектор собственных значений G:")
print(eigenvalues_G)
print(inverse_G)





Определитель G: 23832.000000000007

Вектор собственных значений G:
[ 25.3017166 +0.j -16.85549931+0.j  -4.88519314+0.j  11.43897585+0.j]
[[-0.08215844  0.18680765 -0.1611279   0.23774757]
 [ 0.02517623  0.00302115 -0.02416918  0.02316213]
 [ 0.02324606 -0.05387714  0.09768379 -0.05194696]
 [ 0.04460389 -0.03298087  0.09718026 -0.15563108]]


In [ ]:
#Задание 3
from scipy.linalg import solve
A = np.array([[2, -5, 7],
              [8, 1, 9],
              [3, -4, 12]])

C = np.array([[-25, -17, 78],
              [11, 89, 76],
              [-5, 24, 115]])
B = solve(A, C)

print("Искомая матрица B:")
print(B)

Искомая матрица B:
[[-3.  4.  1.]
 [ 8. 12. -4.]
 [ 3.  5.  8.]]


In [ ]:
#Задание 4
coefficients = np.array([[3, 1, 1, 3],
                         [1, -1, 2, 4],
                         [-5, 0, -1, -7],
                         [1, -6, 28, 6]])
r_s = np.array([28, 7, -5, 3])
res = solve(coefficients, r_s)
print(res)

[-17.775   37.6      6.1125  12.5375]
