<a href="https://colab.research.google.com/github/WYSTANich/PDA_sol-/blob/main/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np

print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [2]:
zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [7]:
vector = np.full(7, 7)
print(vector)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [8]:
start = 10
end = 100
step = 2

even_vector = np.arange(start, end + 1, step)
print(even_vector)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [33]:
np.random.randint(1,10,size = 10)[::-1]

array([7, 3, 9, 9, 6, 8, 9, 5, 6, 9])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [35]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [36]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [23]:
matrix = np.full((4, 4), 7, dtype=int)
np.fill_diagonal(matrix, np.arange(1, 5))
print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [24]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [46]:
matrix_10 = np.random.randint(10,size = (10, 10))
matrix_10 - matrix_10.mean(axis=1,keepdims=True)

array([[-2.2, -1.2, -3.2,  3.8,  3.8,  0.8, -0.2, -2.2,  1.8, -1.2],
       [ 1.2,  0.2, -1.8,  0.2, -1.8, -0.8,  5.2,  0.2, -3.8,  1.2],
       [ 1.6, -1.4, -0.4,  0.6,  1.6,  1.6, -0.4, -2.4,  0.6, -1.4],
       [-1.1,  3.9,  2.9, -3.1, -4.1,  0.9,  2.9, -4.1, -0.1,  1.9],
       [-1. ,  1. , -4. ,  4. ,  4. ,  2. ,  0. ,  0. , -3. , -3. ],
       [ 1.5, -1.5,  2.5, -3.5, -2.5, -2.5,  2.5,  4.5, -3.5,  2.5],
       [-1.9, -0.9,  1.1,  3.1,  1.1,  0.1, -2.9,  3.1, -1.9, -0.9],
       [-3.2,  1.8, -1.2, -1.2,  3.8, -2.2,  0.8, -0.2, -1.2,  2.8],
       [-3.5,  2.5, -0.5, -3.5,  0.5,  3.5,  4.5, -1.5, -2.5,  0.5],
       [-1.1,  2.9, -0.1, -1.1,  2.9,  0.9, -3.1, -2.1, -3.1,  3.9]])

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [47]:
matrix_11= np.random.randint(10,size = (10, 10))
matrix_11 - np.median(matrix_11,axis=0,keepdims=True)

array([[ 4. ,  4. ,  0.5, -2.5, -1. ,  4. ,  2. ,  2. , -2. ,  4.5],
       [ 1. ,  3. ,  0.5, -0.5, -1. , -1. , -1. , -6. , -1. , -4.5],
       [-2. ,  1. ,  1.5, -1.5,  2. ,  0. ,  1. ,  2. ,  0. , -2.5],
       [ 0. , -4. , -1.5,  1.5, -4. ,  3. ,  2. ,  2. , -4. , -4.5],
       [ 0. , -3. ,  0.5,  3.5,  4. , -3. , -3. , -2. ,  0. ,  2.5],
       [-1. ,  3. , -0.5,  2.5, -4. ,  2. , -3. , -2. ,  5. ,  0.5],
       [ 0. , -1. , -5.5,  4.5,  4. ,  2. , -3. , -2. ,  3. ,  2.5],
       [ 5. , -4. , -6.5, -0.5,  1. , -3. , -2. , -2. ,  5. ,  3.5],
       [ 1. , -3. ,  2.5, -1.5,  4. ,  0. ,  5. ,  2. ,  0. , -0.5],
       [-2. ,  4. , -3.5,  0.5, -1. ,  0. ,  2. ,  3. ,  4. , -4.5]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [48]:
matrix_12 = np.random.randint(10,size = (10, 10))
matrix_12.max(axis =1,keepdims=True)
matrix_12.min(axis =1,keepdims=True)
np.concatenate((matrix_12,matrix_12.max(axis =1,keepdims=True),matrix_12.min(axis =1,keepdims=True)),axis = 1)

array([[3, 7, 4, 2, 4, 7, 6, 1, 1, 5, 7, 1],
       [3, 3, 7, 4, 5, 7, 6, 3, 5, 3, 7, 3],
       [4, 8, 6, 2, 8, 6, 6, 3, 1, 3, 8, 1],
       [0, 1, 9, 1, 3, 8, 6, 9, 8, 4, 9, 0],
       [1, 5, 8, 0, 6, 3, 0, 1, 0, 2, 8, 0],
       [1, 5, 2, 7, 9, 9, 2, 8, 6, 4, 9, 1],
       [6, 6, 8, 1, 1, 1, 6, 4, 1, 8, 8, 1],
       [6, 5, 9, 9, 0, 1, 9, 1, 2, 9, 9, 0],
       [5, 6, 4, 7, 7, 4, 4, 5, 7, 6, 7, 4],
       [8, 4, 5, 4, 6, 6, 0, 9, 6, 4, 9, 0]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [31]:
vector_1 =np.mat(np.arange(1,50)[1::2]).reshape(4,6)
vector_2 =np.mat(np.arange(1,50)[2::2]).reshape(6,4)
print(vector_1*vector_2)
print(np.linalg.inv(vector_1*vector_2))

[[1246 1330 1414 1498]
 [2902 3130 3358 3586]
 [4558 4930 5302 5674]
 [6214 6730 7246 7762]]
[[-3.66503876e+11  3.21853878e-04  1.09951163e+12 -7.33007752e+11]
 [-7.33007752e+11  2.19902326e+12 -2.19902326e+12  7.33007752e+11]
 [ 2.56552713e+12 -4.39804651e+12  1.09951163e+12  7.33007752e+11]
 [-1.46601550e+12  2.19902326e+12  0.00000000e+00 -7.33007752e+11]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [11]:
chessmatrix = np.zeros((8, 8), dtype=int)

chessmatrix[1::2, ::2] = 1
chessmatrix[::2, 1::2] = 1

print(chessmatrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
